
import "./globals.css";



export const metadata = {
  title: "Flood Help",
  description: "Generated by create next app",
  charSet: "utf-8"
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <div name="viewport" content="width:device-width, initial-scale=1"></div>
      <body>{children}</body>
    </html>
  );
}
